#!/bin/bash
#our comment is here
echo "The current directory is:"
pwd
echo "The user logged in is:"
whoami
#display user home
echo "Home for the current user is: $HOME"
echo "I have 1$ in my pocket"
#testing veriables
grade=5
person="Adam"
echo "$person is a good boy, he is in grade $grade"
mydir=$(pwd)
echo $mydir
var1=$((5+5))
echo $var1
var2=$(($var1*2))
echo $var2
#if then
if pwd
then
	echo "It works"
fi
#search for a user
user=Lena
if grep $user $HOME
then
	echo "The user $user exists"
else
	echo "The user $user doesn't exist"
fi
#elif
user=anotherUser
if grep $user /etc/passwd
then
	echo "The user $user exists"
elif ls /home
then
	echo "The user doen't exist but anyway there is a directory under /home"
fi
#сравнение чисел
val1=6
if [ $val1 -gt 5 ]
then
	echo "The test value $val1 is greater than 5"
else
	echo "The test value $val1 is not greater than 5"
fi
#сравнение строк
user="Lena"
if [ $user=$USER ]
then
	echo "The user $user is the current logged in user"
fi
#особенности сравнения строк
val1=text
val2="another text"
if [ $val1 \> "$val2" ]
then
	echo "$val1 is greater than $val2"
else
	echo "$val1 is less than $val2"
fi
# сортировка (?)
val1=Likegeeks
val2=likegeeks
if [ $val1 \> $val2 ]
then
	echo "$val1 is greater than $val2"
else
	echo "$val1 is less than $val2"
fi
#Проверка файлов
mydir=/f_2
if [ -d $mydir ]
then
	echo "The $mydir directory exists"
cd $mydir
ls
else
	echo "The $mydir directory does not exist"
fi
